# input : data/external/data.csv
# Example : lowercase, remove punctuation, remove stopwords, remove accents, remove numbers, remove short words, remove long words, remove duplicates ...
# output : data/interim/data.csv
